module: VHGradientView
author: Vidal HARA
author_url: https://github.com/vidalhara
github_url: https://github.com/vidalhara/VHGradientView
copyright: Copyright © 2020 Vidal HARA. VHGradientView released under MIT License.
output: Docs
